naviq_review_final/urls.py
from django.contrib import admin
from django.urls import path
from evaluation.views import *
from django.contrib.auth.views import LoginView, LogoutView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),

    # Home
    path('', home_view, name='home'),

    # Login
    path('login/', LoginView.as_view(template_name='login.html', success_url=reverse_lazy('home')), name='login'),
    path('logout/', LogoutView.as_view(next_page='home'), name='logout'),
    path('register/', register_view, name='register'),

    # Quality Profile
    path("quality-profiles/", QualityProfileListView.as_view(), name="quality_profile_list"),

    # Evaluation
    path('create-evaluation/', create_evaluation_view, name='create_evaluation'),
    path('evaluation/<int:evaluation_id>/question/<int:current_question_index>/', pregunta_siguiente, name='question_and_options'),
    path('evaluation/<int:evaluation_id>/finish/', finalize_evaluation, name='finalize_evaluation'),
    path('evaluation/<int:evaluation_id>/report/', view_evaluation_report, name='view_evaluation_report'),
    path('evaluation/<int:evaluation_id>/update-title/', update_evaluation_title, name='update_evaluation_title'),
    path('update-recommendations/<int:evaluation_id>/', update_recommendations, name='update_recommendations'),
    path('evaluation/update_mvs/<int:evaluation_id>/', update_mvs, name='update_mvs'),
    path('evaluations/', EvaluationListView.as_view(), name='list_evaluations'),
    path('evaluation/<int:pk>/delete/', EvaluationDeleteView.as_view(), name='delete_evaluation'),
    path('evaluation/<int:evaluation_id>/edit/<int:current_question_index>/', edit_evaluation, name='edit_evaluation'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

evaluation/models.py
from decimal import Decimal
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from ckeditor.fields import RichTextField


# Abstract base class for evaluative entities
class EvaluativeEntity(models.Model):
    name = models.CharField(max_length=255)
    description = RichTextField(blank=True, null=True)

    class Meta:
        abstract = True


# Quality Profile Model
class QualityProfile(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    custom = models.BooleanField(default=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Quality Profile"
        verbose_name_plural = "Quality Profiles"


# Criterion Model (inherits from EvaluativeEntity)
class Criterion(EvaluativeEntity):
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Criterion"
        verbose_name_plural = "Criteria"

    def calculate_score(self, quality_profile, user, evaluation):
        total_score = Decimal('0.0')
        detailed_properties = {}  # Dictionary to store detailed scores by property

        quality_profile_criterion = QualityProfileCriterion.objects.get(quality_profile=quality_profile, criterion=self)
        profile_criterion_properties = ProfileCriterionProperty.objects.filter(
            quality_profile_criterion=quality_profile_criterion)

        for profile_criterion_property in profile_criterion_properties:
            # The property's calculate_score_for_user returns a tuple: (score, detailed_applications)
            property_score, property_details = profile_criterion_property.property.calculate_score_for_user(
                user, evaluation, quality_profile_criterion)

            # Aggregate the property scores and weights
            total_score += property_score * profile_criterion_property.property_weight

            # Store the detailed scores for each property along with its weight
            detailed_properties[profile_criterion_property.property.name] = {
                'score': str(property_score),
                'weight': str(profile_criterion_property.property_weight),
                'description': profile_criterion_property.property.description,
                'details': property_details  # Nested details from applications
            }

        return total_score, detailed_properties


# Property Model (inherits from EvaluativeEntity)
class Property(EvaluativeEntity):
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Property"
        verbose_name_plural = "Properties"

    def calculate_score_for_user(self, user, evaluation, quality_profile_criterion):
        # Fetch all ProfileCriterionProperty instances related to this property
        profile_criterion_properties = ProfileCriterionProperty.objects.filter(
            property=self,
            quality_profile_criterion=quality_profile_criterion
        )
        total_score = Decimal('0.0')
        detailed_applications = {}  # To store detailed scores by application

        # Iterate over each ProfileCriterionProperty to handle applications separately
        for profile_criterion_property in profile_criterion_properties:
            applications = Application.objects.filter(
                profilecriterionpropertyapplication__profile_criterion_property=profile_criterion_property
            ).distinct()

            # Check which applications have "N/A" selected by the user
            na_responses = UserResponse.objects.filter(
                user=user,
                selected_options__description="N/A",
                application__in=applications,
                evaluation=evaluation
            )
            applications_with_na = [response.application for response in na_responses]

            # Check if all applications are non-applicable
            if applications.count() == len(applications_with_na):
                # Skip this property as it does not apply
                continue

            # Calculate weights: Only redistribute weights if applications are excluded because of "N/A"
            if applications.count() != applications.exclude(id__in=[app.id for app in applications_with_na]).count():
                weight_per_app = Decimal(1) / Decimal(
                    applications.exclude(id__in=[app.id for app in applications_with_na]).count())
                weights = {app.id: weight_per_app for app in
                           applications.exclude(id__in=[app.id for app in applications_with_na])}
            else:
                # Assign original weights from the ProfileCriterionPropertyApplication if no exclusions
                weights = {app.id: app.profilecriterionpropertyapplication_set.get(
                    profile_criterion_property=profile_criterion_property).app_weight for app in applications}

            # Calculate scores for applications being considered
            for app in applications:
                try:
                    user_response = UserResponse.objects.get(user=user, application=app, evaluation=evaluation)
                    selected_options = user_response.selected_options.all()
                    app_score = app.calculate_score(selected_options)

                    if app_score is not None:
                        # weighted_app_score = app_score * weights[app.id]  # usaba weighted app para mostrar en
                        # reporte pero en realidad se debe mostrar el valor crudo
                        if app not in applications_with_na:
                            total_score += app_score * weights[app.id]

                        detailed_applications[app.name] = {
                            'score': str(app_score),  # aca iria weighted app si se decidiera mostrar el valor agregado
                            'weight': str(weights[app.id]),
                            'description': app.description,
                            'user_response': ', '.join([option.description for option in selected_options])
                        }
                    else:
                        detailed_applications[app.name] = {
                            'score': 'N/A',
                            'weight': 'N/A',
                            'description': app.description,
                            'user_response': ', '.join([option.description for option in selected_options])
                        }
                except UserResponse.DoesNotExist:
                    detailed_applications[app.name] = {
                        'score': '0',
                        'weight': str(weights[app.id] if app.id in weights else 'N/A'),
                        'description': app.description,
                        'note': 'No response found'
                    }
                    continue

        return total_score, detailed_applications


# Application Model (inherits from EvaluativeEntity)
class Application(EvaluativeEntity):
    response_type = models.CharField(max_length=10,
                                     choices=[('single', 'Single Choice'), ('multiple', 'Multiple Choice')],
                                     default='single')
    help_text = RichTextField(blank=True, null=True)
    help_image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Application"
        verbose_name_plural = "Applications"

    def calculate_score(self, selected_options):
        # For single-choice applications
        if self.response_type == "single":
            if len(selected_options) != 1:
                raise ValueError("A single choice application must have exactly one selected option.")
            selected_option = selected_options.first()
            return selected_option.get_value()

        # For multiple-choice applications
        elif self.response_type == "multiple":
            total_score = Decimal(0)
            for option in selected_options:
                if option.description != "N/A":
                    value = option.get_value()
                    if value is not None:
                        total_score += value
            return total_score

        else:
            raise ValueError("Unrecognized response type.")


# Intermediate Model to connect QualityProfile and Criterion, and manage criterion weight
class QualityProfileCriterion(models.Model):
    quality_profile = models.ForeignKey(QualityProfile, on_delete=models.CASCADE)
    criterion = models.ForeignKey(Criterion, on_delete=models.CASCADE)
    criterion_weight = models.DecimalField(max_digits=5, decimal_places=2)

    def __str__(self):
        return f"{self.quality_profile} - {self.criterion}"

    class Meta:
        unique_together = ('quality_profile', 'criterion')
        verbose_name = "Quality Profile Criterion"
        verbose_name_plural = "Quality Profile Criteria"


# Intermediate Model to connect QualityProfile, Criterion, and Property for property weight
class ProfileCriterionProperty(models.Model):
    quality_profile_criterion = models.ForeignKey(QualityProfileCriterion, on_delete=models.CASCADE)
    property = models.ForeignKey(Property, on_delete=models.CASCADE)
    property_weight = models.DecimalField(max_digits=5, decimal_places=2)

    class Meta:
        unique_together = ('quality_profile_criterion', 'property')
        verbose_name = "Quality Profile Criterion Property"
        verbose_name_plural = "Quality Profile Criterion Properties"


# Intermediate Model to connect an Application within a QualityProfile
class ProfileCriterionPropertyApplication(models.Model):
    profile_criterion_property = models.ForeignKey(ProfileCriterionProperty, on_delete=models.CASCADE)

templates/quality_profile/quality_profile_list.html
{% extends "base.html" %}

{% block extra_styles %}
<style>
body {
    color: #404E67;
    background: #F5F7FA;
    font-family: 'Open Sans', sans-serif;
}
.table-wrapper {
    width: 80%;
    margin: 30px auto 50px;
    background: #fff;
    padding: 20px;
    box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.table-title {
    padding-bottom: 10px;
    margin: 0 0 10px;
}
.table-title h2 {
    margin: 6px 0 0;
    font-size: 22px;
}
.table-title .add-new {
    float: right;
    height: 30px;
    font-weight: bold;
    font-size: 12px;
    text-shadow: none;
    min-width: 100px;
    border-radius: 50px;
    line-height: 13px;
    background-color: #fca311;
    border-color: #fca311;
}
.table-title .add-new i {
    margin-right: 4px;
}

.table-responsive{
    padding-bottom: 30px;
}

table.table tr th, table.table tr td {
    border-color: #e9e9e9;
}
table.table th i {
    font-size: 13px;
    margin: 0 5px;
    cursor: pointer;
}
table.table th:last-child {
    width: 100px;
}
table.table td a {
    cursor: pointer;
    display: inline-block;
    margin: 0 5px;
    min-width: 24px;
}

table.table td a.edit {
    color: #FFC107;
}
table.table td a.delete {
    color: #E34724;
}
table.table td i {
    font-size: 19px;
}
table.table td a.add i {
    font-size: 24px;
    margin-right: -1px;
    position: relative;
    top: 3px;
}

.description-column {
    max-width: 200px;
    overflow: hidden;
    text-overflow: ellipsis;
}

/* Estilo zebra para las filas de la tabla anidada */
.criterion-list tr:nth-child(even) {
    background-color: #f2f2f2;
}

.table .actions-column {
    margin: 0 5px; /* Espacio entre iconos */
    min-width: 130px;
}

/* Estilos Modal Eliminar */
.modal-confirm {
  color: #636363;
  width: 400px;
}
.modal-confirm .modal-content {
  padding: 20px;
  border-radius: 5px;
  border: none;
  text-align: center;
  font-size: 14px;
}
.modal-confirm .modal-header {
  display: block;
  text-align: center;
  border-bottom: none;
  position: relative;
}
.modal-confirm h4 {
  text-align: center;
  font-size: 26px;
  margin: 30px 0 -10px;
}
.modal-confirm .close {
  position: absolute;
  top: -5px;
  right: -2px;
}
.modal-confirm .modal-body {
  color: #999;
}
.modal-confirm .modal-footer {
  border: none;
  text-align: center;
  border-radius: 5px;
  font-size: 13px;
  padding: 10px 15px 25px;
}
.modal-confirm .modal-footer a {
  color: #999;
}
.modal-confirm .icon-box {
  width: 80px;
  height: 80px;
  margin: 0 auto;
  border-radius: 50%;
  z-index: 9;
  text-align: center;
  border: 3px solid #f15e5e;
  display: block;
}
.modal-confirm .icon-box i {
  color: #f15e5e;
  font-size: 46px;
  display: inline-block;
  margin-top: 13px;
}
.modal-confirm .btn {
  color: #fff;
  background: #60c7c1;
  text-decoration: none;
  transition: all 0.4s;
  line-height: normal;
  min-width: 120px;
  border: none;
  min-height: 40px;
  border-radius: 3px;
  margin: 0 5px;
  outline: none !important;
}
.modal-confirm .btn-info {
  background: #c1c1c1;
}
.modal-confirm .btn-info:hover, .modal-confirm .btn-info:focus {
  background: #a8a8a8;
}
.modal-confirm .btn-danger {
  background: #f15e5e;
}
.modal-confirm .btn-danger:hover, .modal-confirm .btn-danger:focus {
  background: #ee3535;
}

.close-delete-modal{
    margin-left: 90% !important;
}

.btn-info.add-new {
    color: white;
    background-color: #FCA311;
}

.btn-info.add-new:hover,
.btn-info.add-new:active,
.btn-info.add-new:focus-visible {
    background-color: #f7931e;
    color: white;
    border-color: #f7931e;
}

</style>
{% endblock %}

{% block title %}
Quality Profiles List
{% endblock %}

{% block content %}
<div class="container-lg">
    <div class="table-responsive">
        <div class="table-wrapper">
            <div class="table-title">
            <!-- New button in its own row -->
{#                <div class="row">#}
{#                    <div class="col-12">#}
{#                        {% if user.is_authenticated %}#}
{#                            <button type="button" class="btn btn-info add-new" onclick="window.location='{% url 'add_profile' %}'">#}
{#                                <i class="fa fa-plus"></i> New#}
{#                            </button>#}
{#                        {% endif %}#}
{#                    </div>#}
{#                </div>#}
                <!-- Title in its own row -->
                <div class="table-title">
                    <div class="row">
                        <div class="col-sm-8"><h2 class="display-5 fw-bold">Quality Profiles</h2><br></div>
                        <p>Quality Profiles are tailored sets of criteria and properties specifically configured for distinct evaluation contexts or use cases. They enable users to customize the evaluation process according to the unique needs and goals of their visualization project. Each Quality Profile determines which quality criteria are more critical and assigns appropriate weights to them, ensuring that the evaluation focuses on the most relevant aspects for the given context. Users can select from standard profiles or create and save their custom profiles, facilitating targeted and meaningful assessments of narrative visualizations.</p>
                    </div>
                </div>
            </div>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>Quality Profile Name</th>
                        <th>Description</th>
                        <th>Details</th>
                        {% if user.is_authenticated %}
                            <th>Actions</th>
                        {% endif %}
                    </tr>
                </thead>
                <tbody>
                    {% for profile in qualityprofiles %}
                    <tr class="align-middle">
                        <!-- Nombre del perfil -->
                        <td>{{ profile.name }}</td>
                        <!-- Descripción del perfil -->
                        <td class="description-column">{{ profile.description }}</td>
                         <!-- Criterios del perfil -->
                        <td class="criterion-list">
                            <table class="table table-sm table-borderless">
                                <tbody>
                                    {% for quality_profile_criterion in profile.qualityprofilecriterion_set.all %}
                                        <tr>
                                            <td>{{ quality_profile_criterion.criterion.name }}</td>
                                            <td>{{ quality_profile_criterion.criterion_weight }}</td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </td>
                        {% if user.is_authenticated %}
                            <td class="actions-column">
                                {% if profile.custom and profile.user == user %}
                                    <!-- Botón de editar -->
{#                                    <a href="{% url 'edit_profile' profile.id %}" title="Edit" data-toggle="tooltip" class="edit"><i class="material-icons">&#xE254;</i></a>#}
                                    <!-- Botón de eliminar -->
{#                                    <a href="#" title="Delete" data-toggle="modal" data-tooltip="tooltip" data-target="#deleteModal" data-id="{{ profile.id }}" class="delete"><i class="material-icons">&#xE872;</i></a>#}
                                {% elif profile.custom and profile.user != user %}
                                    Private
                                {% else %}
                                    Default
                                {% endif %}
                            </td>
                        {% else %}
                            <td>–</td>
                        {% endif %}
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!-- Confirm Delete Modal -->
{#<div id="deleteModal" class="modal fade">#}
{#  <div class="modal-dialog modal-confirm">#}
{#    <div class="modal-content">#}
{#      <div class="modal-header">#}
{#        <button type="button" class="btn-close close-delete-modal" data-bs-dismiss="modal" aria-hidden="true"></button>#}
{#        <div class="icon-box">#}
{#          <i class="fa fa-trash"></i>#}
{#        </div>#}
{#        <h4 class="modal-title">Delete Quality Profile</h4>#}
{#      </div>#}
{#      <div class="modal-body">#}
{#        <p>Are you sure you want to delete this profile? This process cannot be undone.</p>#}
{#      </div>#}
{#      <div class="modal-footer justify-content-center">#}
{#        <button type="button" class="btn btn-info" data-bs-dismiss="modal">Cancel</button>#}
{#        <button type="button" class="btn btn-danger" id="confirmDelete">Delete</button>#}
{#      </div>#}
{#    </div>#}
{#  </div>#}
{#</div>#}

{% block extra_scripts %}


{#<script>#}
{#$(document).ready(function(){#}
{#    $.ajaxSetup({#}
{#        headers: {#}
{#            'X-CSRFToken': '{{ csrf_token }}'#}
{#        }#}
{#    });#}
{##}
{#    $('[data-toggle="tooltip"]').tooltip();#}
{#    $('[data-tooltip="tooltip"]').tooltip();#}
{##}
{#    // Function to show success alert#}
{#    function showSuccessAlert(containerSelector) {#}
{#        var successAlert = '<div class="alert alert-success alert-dismissible fade show" role="alert">' +#}
{#                           'Quality profile successfully removed!' +#}
{#                           '</div>';#}
{#        $(containerSelector).prepend(successAlert);#}
{#    }#}
{##}
{#    // Function to handle the deletion#}
{#    function handleDeletion(profileId) {#}
{#        $('#confirmDelete').prop('disabled', true).text('Deleting...');#}
{#        $.ajax({#}
{#            url: `/quality-profile/${profileId}/delete/`,#}
{#            type: 'POST',#}
{#            success: function(response) {#}
{#                $('#deleteModal').modal('hide');#}
{#                // Show success alert#}
{#                showSuccessAlert('.container-lg');#}
{#                // Wait for 2 seconds before reloading to allow the alert to be seen#}
{#                setTimeout(function() { location.reload(); }, 2000);#}
{#            },#}
{#            error: function(response) {#}
{#                $('#confirmDelete').prop('disabled', false).text('Delete');#}
{#                console.error('Error deleting profile.');#}
{#                alert('There was an error deleting the profile.'); // Replace with a more user-friendly error message#}
{#            }#}
{#        });#}
{#    }#}
{##}
{#    // Delegate the show modal event to the dynamic .delete button using the table as the parent#}
{#    $('.table').on('click', '.delete', function (event) {#}
{#        var button = $(this); // The delete button that was clicked#}
{#        var profileId = button.data('id');#}
{#        var modal = $('#deleteModal');#}
{##}
{#        modal.find('#confirmDelete').off('click').on('click', function() {#}
{#            handleDeletion(profileId);#}
{#        });#}
{##}
{#        // Trigger the modal to open#}
{#        modal.modal('show');#}
{#    });#}
{#});#}
{#</script>#}
{% endblock %}
{% endblock %}